"""Reviewed longer AddonTransient messages; {@N} preserves the Nth SeString tag."""

import json
import pathlib
import re

PATH = pathlib.Path(__file__).resolve().parents[1] / "data/da_revisionare/system/addontransient.json"
TAG = re.compile(r"<hex:[0-9A-Fa-f]+>")
SLOT = re.compile(r"\{@(\d+)\}")

TEXT = {
    413: "Alcuni avatar potrebbero non essere autorizzati ad accompagnarti in determinate spedizioni istanziate.",
    1014: "Questo menu mostra i sodalizi che stanno reclutando membri. Puoi filtrare i risultati per attività e lingua.",
    1030: "Selezionando un oggetto collezionabile nella finestra di raccolta si aprirà l'interfaccia dei collezionabili. Qui potrai cercare di aumentarne il grado di collezionabilità prima di aggiungerlo all'inventario.",
    1026: "{@0}{@1}■Ma Aspetta...{@2}{@3}{@4}{@5}Sjeros, a Gangos, e i tuoi compagni della Resistenza sul fronte meridionale possono darti ulteriori informazioni. Non esitare a parlare con loro!",
    1028: "Più alta è la collezionabilità di un oggetto, più interesse suscita negli NPC che desiderano acquistarlo o scambiarlo. Prima di poterlo accettare, però, gli NPC richiedono che raggiunga una determinata soglia di collezionabilità.",
    411: "Il sistema dei glamour si sblocca per gli avatar NPC che hanno raggiunto il livello 80. Usa le icone {@0}{@1}Glamour{@2}{@3} o il sottocomando nella finestra di selezione del gruppo per modificarne l'aspetto.",
    433: "Quando ti iscrivi a un incarico, questo appare nella lista degli incarichi insieme a un'icona. Selezionalo per controllare lo {@0}{@1}stato dell'incarico{@2}{@3}, compresi i progressi nell'abbinamento e il tempo di attesa stimato.",
    1042: "Quando usi le azioni per collezionabili, potresti ottenere l'effetto {@0}{@1}Stendardo del Collezionista{@2}{@3}. Finché è attivo, l'efficacia delle azioni audaci e meticolose aumenta notevolmente.",
    1063: "I titolari dei diritti possono espellere giocatori specifici dall'edificio o dal giardino della tenuta e vietare loro l'accesso alla proprietà per un periodo di tempo.{@0}{@1}Dal menu Sociale, seleziona «Alloggi», poi «Impostazioni della Tenuta» e infine «Diritti del Titolare della Tenuta» per modificare le relative impostazioni.",
    1010: "Mostra l'elenco dei membri del sodalizio. Qui puoi svolgere varie attività amministrative, come nominare amministratori e trasferire i privilegi del fondatore.{@0}{@1}Puoi anche inserire giocatori nella lista nera: verranno rimossi dal sodalizio e non potranno più rientrarvi.",
    1038: "L'efficacia delle azioni per collezionabili, come Scour, può essere aumentata usando prima {@0}{@1}Scrutinio{@2}{@3}. Questa azione consuma GP senza ridurre l'integrità del punto di raccolta. Un valore di percezione più alto ne aumenta l'efficacia.",
    423: "Negli incarichi della storia principale di livello 71 o superiore puoi scegliere i tuoi {@0}{@1}NPC di supporto{@2}{@3} preferiti per formare un gruppo. Seleziona un membro del gruppo attuale per vedere tutti i {@4}{@5}membri disponibili{@6}{@7}.",
    1048: "La collezionabilità è un altro modo per misurare la qualità intrinseca di un oggetto.{@0}{@1}Il valore richiesto per consegnarlo è indicato nell'angolo superiore destro dell'interfaccia.{@2}{@3}Quando scomponi gli oggetti mediante riduzione eterea, questo valore indica la collezionabilità necessaria per ottenere oggetti diversi dai cristalli.",
    1008: "Tutti i membri del sodalizio possono pubblicare commenti nella bacheca.{@0}{@1}Sono visibili fino a 100 commenti; i più vecchi vengono eliminati per primi. Il fondatore e gli amministratori possono cancellarli in qualsiasi momento.{@2}{@3}* I personaggi della prova gratuita non possono scrivere nella bacheca durante i primi 14 giorni di appartenenza al sodalizio.",
    1044: "Quando raccogli collezionabili, aumentare la collezionabilità non è l'unica cosa importante. Anche le azioni che aumentano la probabilità di raccolta, concedono tentativi aggiuntivi o ripristinano l'integrità sono fondamentali per ottenere il maggior numero possibile di oggetti. Pianificare e usare bene tutte le azioni è la chiave del successo per ogni esperto Discepolo della Terra.",
    1040: "Usando le azioni per collezionabili, potresti attivare {@0}{@1}Intuizione del Collezionista{@2}{@3}, che concede un bonus alla collezionabilità. Una percezione più alta aumenta la probabilità di attivare questo bonus.{@4}{@5}※Puoi aumentarla anche usando Concentrazione del Collezionista.",
    1024: "Se dimostri sufficiente valore quando fai rapporto al comandante della Resistenza, il tuo grado nella Resistenza aumenterà. Un grado più alto permette di accedere a nuove aree del fronte e a ulteriori missioni.{@0}{@1}{@2}* Il tuo grado non aumenterà senza l'autorizzazione del comandante, quindi non dimenticare di presentarti per la valutazione!{@3}",
    1025: "{@0}{@1}■Avanzamento di Livello{@2}{@3}{@4}{@5}Completando un'operazione militare otterrai punti esperienza ordinari oltre al valore nella Resistenza. L'esperienza farà salire normalmente il livello della classe: per sfruttarla al meglio, considera l'uso di una classe che non abbia ancora raggiunto il livello 80.",
    1051: "Puoi accedere a una spedizione variante o criterion dalla finestra di ricerca delle spedizioni V&C, parlando con l'NPC all'ingresso oppure scegliendo {@0}{@1}Incarichi{@2}{@3} dal menu principale.{@4}{@5}Questa finestra mostra tutte le informazioni necessarie per entrare e le impostazioni specifiche della spedizione.",
    1022: "{@0}{@1}■Sincronizzazione del Livello{@2}{@3}{@4}{@5}Puoi entrare nel fronte meridionale di Bozja dal livello 71, ma durante l'incarico tutti i giocatori vengono sincronizzati al livello 80. Anche il livello dell'equipaggiamento viene sincronizzato.{@6}{@7}{@8}* Durante l'incarico saranno disponibili tutte le azioni di classe sbloccabili fino al livello 80.{@9}",
    1021: "{@0}{@1}Le regole di combattimento sul fronte meridionale di Bozja sono diverse da quelle che hai affrontato finora. Le pagine seguenti spiegano in dettaglio cosa aspettarti sul campo di battaglia.{@2}{@3}{@4}{@5}{@6}Leggile con attenzione se vuoi prevalere sulla IV Legione dell'Impero.{@7}",
    429: "La {@0}{@1}Ricerca Incarichi{@2}{@3} permette di affrontare spedizioni e altri incarichi con un {@4}{@5}gruppo di giocatori{@6}{@7}. Puoi aprirla scegliendo {@8}{@9}Incarichi{@10}{@11} dal menu principale, oppure selezionando l'opzione corrispondente all'ingresso di un incarico.",
    1071: "A seconda del tipo di tenuta, potresti non poter vietare l'accesso ad alcuni personaggi. Anche se aggiunti all'elenco dei personaggi esclusi, quelli esenti non verranno espulsi né si vedranno negare l'accesso.{@0}{@1}Non è possibile escludere i seguenti personaggi:{@2}・Il titolare principale dei diritti{@3}・I membri della tenuta della compagnia libera{@4}・Gli inquilini degli alloggi personali condivisi{@5}",
    1046: "Gli oggetti collezionabili pregiati con collezionabilità massima possono talvolta fornire oggetti estremamente rari tramite la riduzione eterea.{@0}{@1}Inoltre, se raccolti con collezionabilità massima, questi oggetti possono diventare sublimi, garantendo oggetti rari con la riduzione eterea.{@2}{@3}Una maggiore probabilità di raccolta aumenta la possibilità che un oggetto pregiato diventi sublime.",
    1036: "Quando l'oggetto raggiunge una collezionabilità sufficiente, usa l'azione {@0}{@1}Raccogli{@2}{@3} per ottenerlo e aggiungerlo all'inventario. Ogni oggetto raccolto riduce di uno l'integrità del punto di raccolta; quando questa arriva a zero, non puoi raccoglierne altri.{@4}{@5}※Se la probabilità di raccolta è inferiore al 100%, il tentativo potrebbe fallire.",
    1057: "Le spedizioni varianti presentano {@0}{@1}percorsi alternativi{@2}{@3}. Esplorandoli insieme al personaggio della missione, scoprirai nuovi elementi della storia.{@4}{@5}Completando un percorso, aggiungerai una voce al diario o al registro della spedizione. Per consultare quelle completate, apri la finestra di ricerca delle spedizioni V&C e seleziona il ritratto del personaggio.",
    1073: "Rinnova gli interni di una tenuta con la funzione di progettazione degli interni.{@0}{@1}Dal menu Sociale seleziona «Alloggi», poi «Progettazione degli Interni» per aprire la finestra in cui scegliere lo stile desiderato.{@2}{@3}Una volta applicato, tutto l'interno cambierà, eccetto carta da parati, pavimentazione e luci a soffitto. Potrebbe cambiare anche la disposizione dei piani, compresa la posizione delle scale.",
    409: "Puoi affrontare di nuovo le spedizioni della storia principale di livello 71 o superiore già completate con un gruppo di {@0}{@1}avatar NPC{@2}{@3}. Gli avatar ottengono esperienza e salgono di livello partecipando agli incarichi.{@4}{@5}{@6}{@7}※Quando usi il sistema Trust, gli scrigni dell'incarico contengono meno oggetti e alcuni nemici non rilasciano più ricompense.{@8}{@9}",
    1032: "Puoi usare tecniche come {@0}{@1}Scour{@2}{@3} per aumentare la collezionabilità di un oggetto. Queste azioni, però, riducono l'{@4}{@5}integrità{@6}{@7} del punto di raccolta. Anche raccogliere oggetti la riduce: scegli con cura le azioni per conservare abbastanza integrità dopo aver raggiunto la collezionabilità desiderata.",
    1065: "Solo i personaggi designati come titolari dei diritti possono usare le relative funzioni. Il titolare principale viene determinato automaticamente in base al tipo di tenuta. In alcuni casi è possibile nominare anche titolari secondari.{@0}{@1}Per le tenute delle compagnie libere, il capo della compagnia è il titolare principale e può nominare titolari secondari tra i membri della tenuta condivisa.{@2}{@3}Gli appartamenti e le stanze private possono avere solo un titolare principale.",
    1077: "Solo chi ha ricevuto le autorizzazioni necessarie può modificare il design degli interni di una tenuta.{@0}{@1}Tenute delle compagnie libere: possono farlo i membri autorizzati sia a ristrutturare l'edificio sia a collocare gli arredi.{@2}{@3}Tenute private: oltre ai proprietari, possono farlo gli inquilini autorizzati ad aggiungere, rimuovere o modificare posizione e colore degli arredi o delle pareti.",
    1006: "■Messaggio del Giorno{@0}Lascia un messaggio per i membri del sodalizio: un motto, un annuncio o qualsiasi altra cosa. Possono pubblicarlo il fondatore e gli amministratori.{@1}{@2}■Sondaggio{@3}Il fondatore e gli amministratori possono creare sondaggi. Ogni membro può esprimere un voto per sondaggio.{@4}{@5}■Avvisi{@6}Pubblica fino a cinque avvisi alla volta. Questa funzione è riservata al fondatore e agli amministratori.",
    419: "Dopo l'iscrizione, quando l'incarico sarà disponibile, apparirà una finestra accompagnata da un {@0}{@1}segnale acustico{@2}{@3}. Seleziona {@4}{@5}Inizia{@6}{@7} per avviarlo.{@8}{@9}{@10}{@11}※Se non inizi l'incarico entro il tempo limite, l'iscrizione verrà annullata automaticamente e dovrai ripetere la procedura.{@12}{@13}",
    1061: "A differenza delle spedizioni varianti, le spedizioni criterion {@0}{@1}non consentono di cambiare classe{@2}{@3}. Anche la resurrezione tramite Raise o altre abilità è limitata: è consentita solo con l'azione speciale Variant Raise II.{@4}{@5}Nelle spedizioni criterion di difficoltà {@6}{@7}Savage{@8}{@9} le azioni varianti sono completamente disattivate. È necessario formare in anticipo un gruppo di quattro giocatori che soddisfi i requisiti d'accesso.",
    1069: "La consultazione della lista nera impedisce automaticamente ai personaggi presenti nella lista nera di un titolare dei diritti di accedere alla proprietà. Quando nella tenuta è presente un titolare principale o secondario che ha attivato questa funzione, i personaggi della sua lista nera non possono entrare. Se tentano di farlo, vengono aggiunti automaticamente all'elenco dei personaggi esclusi.{@0}{@1}Puoi attivare o disattivare la funzione con la casella a sinistra del nome del personaggio nelle «Impostazioni dei Titolari dei Diritti».",
    435: "Dopo l'abbinamento con altri giocatori, apparirà una finestra accompagnata da un {@0}{@1}segnale acustico{@2}{@3}. Seleziona {@4}{@5}Inizia{@6}{@7} per avviare l'incarico.{@8}{@9}{@10}{@11}※Se non inizi l'incarico entro il tempo limite, l'iscrizione verrà annullata automaticamente e dovrai ripetere la procedura.{@12}{@13}",
    1023: "{@0}{@1}■Grado nella Resistenza{@2}{@3}{@4}{@5}Al fronte, tutti i giocatori seguono un sistema di avanzamento separato, indicato dal «grado nella Resistenza». Distinguendoti in battaglie su larga scala, come schermaglie e scontri decisivi, otterrai «valore», simile ai punti esperienza.{@6}{@7}{@8}* Sconfiggere truppe imperiali e bestie non basta a dimostrare il tuo valore: devi partecipare a operazioni militari riuscite.{@9}",
    431: "Accedi a spedizioni e altri incarichi dalla {@0}{@1}Ricerca Incarichi{@2}{@3}: scegli l'incarico desiderato e seleziona {@4}{@5}Partecipa{@6}{@7}. Verrai abbinato automaticamente ad altri giocatori diretti allo stesso incarico.{@8}{@9}{@10}{@11}※Puoi iscriverti a un massimo di cinque incarichi alla volta.{@12}※Gli incarichi contrassegnati da un lucchetto richiedono il soddisfacimento di determinate condizioni prima di poter essere affrontati.{@13}{@14}",
    1075: "Puoi modificare il design degli interni di villette, case e ville.{@0}{@1}Per applicare un nuovo stile, tutti gli arredi collocati vengono spostati nel magazzino. Se lo spazio nel magazzino non è sufficiente, non puoi completare la modifica.{@2}{@3}Non puoi inoltre modificare gli interni nei quindici giorni precedenti la demolizione automatica della tenuta.{@4}{@5}{@6}{@7}※Non è possibile modificare il design degli interni di appartamenti e stanze private.{@8}{@9}",
    1059: "Hai sbloccato le {@0}{@1}spedizioni criterion{@2}{@3}, una categoria di sfide più difficili accessibile cambiando scheda nella parte superiore della finestra di ricerca delle spedizioni V&C.{@4}{@5}Le spedizioni criterion non prevedono NPC accompagnatori né percorsi alternativi da esplorare. La scheda mostra invece l'elenco delle spedizioni disponibili e la quantità di {@6}{@7}valuta speciale{@8}{@9} ottenuta completando queste sfide più impegnative.",
    415: "Puoi affrontare una spedizione in due modi: con il {@0}{@1}supporto di NPC fidati{@2}{@3} oppure formando un gruppo {@4}{@5}con altri giocatori{@6}{@7}. Puoi creare il gruppo in anticipo o usare la Ricerca Incarichi. In entrambi i casi, la difficoltà e l'esperienza offerte dall'incarico saranno comparabili.{@8}{@9}{@10}{@11}※Quando affronti un incarico con gli NPC, gli scrigni contengono meno oggetti e alcuni nemici non rilasciano più ricompense.{@12}{@13}",
    417: "Selezionando {@0}{@1}Supporto Incarichi{@2}{@3} da {@4}{@5}Incarichi{@6}{@7} nel menu principale, oppure interagendo con l'ingresso di un incarico compatibile, puoi evocare una {@8}{@9}squadra di NPC alleati{@10}{@11}. I gruppi di NPC vengono {@12}{@13}bilanciati automaticamente{@14}{@15} in base alla tua classe. Quando sei pronto, seleziona {@16}{@17}Iscriviti all'incarico{@18}{@19} e preparati alla battaglia!",
    421: "Man mano che prosegui nell'avventura, il numero di incarichi disponibili aumenta. Se un incarico non prevede il supporto degli NPC, usa la {@0}{@1}Ricerca Incarichi{@2}{@3} per unirti ad altri giocatori. Puoi anche ripetere gli incarichi già completati usando la {@4}{@5}Ricerca Incarichi{@6}{@7} o il {@8}{@9}Supporto Incarichi{@10}{@11}, entrambi accessibili da {@12}{@13}Incarichi{@14}{@15} nel menu principale.",
    437: "Man mano che prosegui nell'avventura, il numero di incarichi disponibili aumenta. Molti possono essere completati sia con la {@0}{@1}Ricerca Incarichi{@2}{@3} sia con il {@4}{@5}Supporto Incarichi{@6}{@7}, quindi impara a usare entrambi i sistemi. Puoi anche ripetere le spedizioni già completate scegliendo {@8}{@9}Ricerca Incarichi{@10}{@11} o {@12}{@13}Supporto Incarichi{@14}{@15} da {@16}{@17}Incarichi{@18}{@19} nel menu principale.",
    1053: "La difficoltà di una {@0}{@1}spedizione variante{@2}{@3} si adatta automaticamente a gruppi da uno a quattro giocatori. Vincere richiede impegno e attenzione, ma puoi completarla anche da solo.{@4}{@5}Se vuoi entrare da solo o con il tuo gruppo attuale, deseleziona {@6}{@7}Abilita Abbinamento del Gruppo{@8}{@9} (disattivata per impostazione predefinita). Attivando questa opzione, verrai invece abbinato ad altri avventurieri in un gruppo di quattro.",
    1004: "I sodalizi riuniscono giocatori con interessi comuni. Ognuno può avere fino a 1.000 membri ed è un ottimo modo per conoscere e frequentare altri avventurieri.{@0}{@1}Chiunque può creare un sodalizio o unirsi a uno esistente. I sodalizi sono condivise tra mondi diversi e puoi far parte di un massimo di dieci alla volta.{@2}{@3}Per cercare i sodalizi che stanno reclutando, scegli {@4}{@5}Sociale{@6}{@7} dal {@8}{@9}menu principale{@10}{@11}, poi {@12}{@13}Ricerca dei Sodalizi{@14}{@15}.{@16}{@17}Ogni sodalizio è guidato da un fondatore, che può concedere privilegi amministrativi ad altri membri. Il ruolo spetta inizialmente a chi crea il sodalizio, ma può essere trasferito.{@18}{@19}Unisciti a un sodalizio o creane uno tuo per usufruire dei suoi numerosi vantaggi!",
    1012: "■Impostazioni{@0}Questo menu è accessibile solo al fondatore. Qui puoi rinominare il sodalizio, impostarne le attività, gestire la lista nera e scioglierlo.{@1}{@2}■Reclutamento{@3}Questo menu permette di reclutare nuovi membri. Il reclutamento termina quando si raggiunge l'obiettivo, trascorre una settimana o chi l'ha avviato decide di annullarlo.{@4}{@5}■Amministrazione{@6}Il fondatore può nominare amministratori per aiutarlo a gestire il sodalizio. I privilegi del fondatore possono essere trasferiti solo a un amministratore. Prima di lasciare il sodalizio, il fondatore deve trasferire tali privilegi.",
    1034: "Tre azioni principali aumentano la collezionabilità; ciascuna riduce di uno l'integrità del punto di raccolta.{@0}{@1}Scour{@2}Aumenta la collezionabilità di una quantità fissa determinata dal valore di raccolta.{@3}{@4}Brazen Prospector / Brazen Woodsman{@5}Aumenta la collezionabilità di una quantità casuale, che può essere inferiore o molto superiore a quella di Scour. Può essere utile quando l'oggetto desiderato è abbondante nel punto di raccolta.{@6}{@7}Meticulous Prospector / Meticulous Woodsman{@8}Aumenta la collezionabilità di una quantità fissa inferiore a quella di Scour, ma potrebbe non ridurre l'integrità. È utile se la prossima azione raggiungerà sicuramente la collezionabilità richiesta.",
    1055: "Per offrire maggiore libertà nella scelta del ruolo, le spedizioni varianti mettono a disposizione {@0}{@1}azioni varianti{@2}{@3}.{@4}{@5}Queste imitano abilità esistenti come {@6}{@7}Cure{@8}{@9} o {@10}{@11}Rampart{@12}{@13}, riducendo la necessità di avere tank, attaccanti o guaritori dedicati. Ogni giocatore può usare due azioni nella spedizione e cambiarle {@14}{@15}in qualsiasi momento{@16}{@17} con il pulsante {@18}{@19}Imposta Azioni{@20}{@21} nella finestra di ricerca delle spedizioni V&C.",
    1067: "I personaggi a cui hai vietato l'accesso alla proprietà compaiono nell'elenco dei personaggi esclusi. I titolari principali e secondari possono aprire l'elenco selezionando «Personaggi Esclusi» nella finestra dei diritti del titolare della tenuta.{@0}{@1}Per escludere un personaggio, devi trovarti nella tenuta e avere l'autorizzazione necessaria. Seleziona il personaggio, scegli «Vieta Accesso alla Proprietà» nei sottocomandi e poi «Registra come Personaggio Escluso».{@2}{@3}I personaggi restano nell'elenco per 10 giorni, durante i quali non possono entrare nell'edificio o nel giardino della tenuta.{@4}{@5}I titolari principali possono rimuoverli dall'elenco in qualsiasi momento.",
    446: "Per visualizzare le registrazioni degli incarichi devono essere soddisfatte queste condizioni:{@0}　1. Ti trovi in una stanza della locanda.{@1}　2. L'incarico registrato appartiene alla versione più recente del gioco.{@2}{@3}{@4}{@5}1. Ti trovi in una stanza della locanda{@6}{@7}{@8}La riproduzione delle registrazioni è disponibile solo nelle stanze della locanda.{@9}{@10}{@11}{@12}2. L'incarico registrato appartiene alla versione più recente del gioco{@13}{@14}{@15}Questo vale sia per gli aggiornamenti principali sia per le correzioni minori.{@16}Le registrazioni non saranno più accessibili dopo l'applicazione dell'ultima patch dei dati.",
    1020: "{@0}■Assistenza alle Esibizioni{@1}{@2}Questa funzione ti aiuta a suonare diversi brani, mostrando i tempi e i tasti da premere durante l'esecuzione.{@3}{@4}{@5}■Uso dell'Assistenza alle Esibizioni{@6}{@7}Segui questi passaggi per usarla:{@8} 1. Seleziona Assistenza alle Esibizioni dal menu Esibizione.{@9} 2. Scegli un brano.{@10} 3. Imposta la velocità di riproduzione e scegli se usare il metronomo.{@11}{@12}{@13}■Importante{@14}{@15}Se un membro del gruppo avvia una verifica di prontezza per la Modalità Concerto mentre usi l'Assistenza alle Esibizioni, verrà inviata automaticamente la risposta «No». Per questo motivo, è sconsigliato usarla mentre sei in un gruppo.{@16}",
    450: "{@0}{@1}Pausa{@2}{@3}{@4}Interrompe temporaneamente la riproduzione.{@5}{@6}{@7}{@8}Selezione Capitolo{@9}{@10}{@11}Avvia la riproduzione dal punto selezionato.{@12}※A seconda del capitolo, l'avvio potrebbe non essere immediato.{@13}{@14}{@15}{@16}Capitolo Successivo{@17}{@18}{@19}Passa al prossimo capitolo disponibile.{@20}{@21}{@22}{@23}Capitolo Precedente{@24}{@25}{@26}Torna al capitolo precedente.{@27}{@28}{@29}{@30}Mostra HUD{@31}{@32}{@33}Mostra o nasconde gli elementi dell'interfaccia sullo schermo.{@34}※Le impostazioni vengono salvate per la prossima riproduzione.{@35}{@36}{@37}{@38}Bersaglio Focale{@39}{@40}{@41}Mostra le informazioni del bersaglio focale selezionato.{@42}{@43}{@44}{@45}Esci{@46}{@47}{@48}Termina la riproduzione.",
    444: "Per usare il Registratore Incarichi devono essere soddisfatte queste condizioni:{@0}　1. Il registratore è attivo.{@1}　2. L'incarico attuale può essere registrato.{@2}　3. Il gruppo soddisfa i requisiti numerici minimi.{@3}　4. È stata eseguita la verifica di prontezza alla registrazione.{@4}{@5}{@6}{@7}1. Il registratore è attivo{@8}{@9}{@10}Puoi modificarne le impostazioni da {@11}{@12}Registratore Incarichi{@13}{@14} nel menu principale.{@15}{@16}{@17}{@18}2. L'incarico attuale può essere registrato{@19}{@20}{@21}Non tutti gli incarichi possono essere registrati.{@22}Quelli compatibili sono contrassegnati da un'icona speciale.{@23}{@24}{@25}{@26}3. Il gruppo soddisfa i requisiti numerici minimi{@27}{@28}{@29}Gli incarichi affrontati con un gruppo troppo piccolo non possono essere registrati.{@30}※Questo vale anche per i gruppi formati tramite la Ricerca Incarichi.{@31}※Gli incarichi con l'opzione Gruppo Senza Restrizioni attiva non possono essere registrati, anche se il gruppo soddisfa il numero minimo di membri.{@32}{@33}{@34}{@35}4. È stata eseguita la verifica di prontezza alla registrazione{@36}{@37}{@38}Prima di iniziare la registrazione è necessaria l'approvazione di tutti i membri del gruppo.{@39}※La verifica deve essere effettuata entro 5 minuti dall'inizio dell'incarico.{@40}{@41}Puoi salvare solo 3 registrazioni alla volta; le più vecchie verranno sovrascritte.{@42}※Puoi proteggerne fino a 2 alla volta.",
    1018: "{@0}■Panoramica{@1}{@2}La Modalità Concerto aiuta te e gli altri membri del gruppo a suonare in sincronia per il pubblico.{@3}{@4}{@5}■Differenze di Riproduzione tra Esibizione e Modalità Concerto{@6}{@7}Con la Modalità Concerto attiva, i giocatori nelle vicinanze sentiranno tutti i membri del gruppo in sincronia. Chi suona, invece, percepirà un ritardo tra la pressione dei tasti e il suono, variabile secondo il tipo di riproduzione.{@8}Con «Solo Io» sentirai solo il tuo strumento; con «Tutti i Membri» sentirai gli strumenti di tutti, con un ritardo maggiore.{@9}※«Tipo di Riproduzione» si trova nelle impostazioni della Modalità Concerto.{@10}{@11}{@12}■Attivare la Modalità Concerto{@13}{@14}Segui questi passaggi:{@15} 1. Seleziona «Verifica di Prontezza Concerto» dal menu del metronomo.{@16} 2. Attiva «Entra in Modalità Concerto» e seleziona Inizia.{@17} 3. Quando tutti i membri del gruppo avranno risposto alla verifica, entrerai nella Modalità Concerto.{@18}{@19}{@20}■Requisiti della Modalità Concerto{@21}{@22}Puoi usarla solo se sono soddisfatte le condizioni seguenti:{@23} 1. Il capogruppo sta usando la modalità Esibizione.{@24} 2. Tutti i membri si trovano in un'area dove è possibile usare le azioni di esibizione. La Modalità Concerto non è disponibile nelle stanze della locanda né nelle caserme della Grande Compagnia.{@25} 3. Ogni area può ospitare un numero limitato di concerti contemporaneamente. Se è stato raggiunto il limite, non puoi usare la Modalità Concerto in quell'area.{@26}",
}


def main():
    rows = json.loads(PATH.read_text(encoding="utf-8"))
    for row_id, template in TEXT.items():
        row = rows[str(row_id)]
        if row["translation"]:
            continue
        tags = TAG.findall(row["original"])
        indices = [int(match.group(1)) for match in SLOT.finditer(template)]
        assert indices == list(range(len(tags))), (row_id, indices, len(tags))
        row["translation"] = SLOT.sub(lambda match: tags[int(match.group(1))], template)
    PATH.write_text(json.dumps(rows, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
